### ISSUE TITLE
Migrate to Commander

### ISSUE THREAD

**Issue by alex-saunders** [alex-saunders/glicky#18]
It would be great to use [commander](https://github.com/tj/commanders) for the CLI commands for glicky. 
Commander offers automatic generation of the `--help` command, which details all possible options you can pass, as well as a much more scalable architecture for adding commands/options in the future.

It would also be nice to add the `--version`, `-v` command while we're at it, which would grab the current version number from package.json and return it

**Comment by Tolsee** [comment]
Seems like a good idea, because of the fact that the commander provides a really easy interface for CLI tools. I will start working on this. I am going to open a PR asap. Maybe you can set this issue as taken @alex-saunders

**Comment by alex-saunders** [comment]
sure @Tolsee , I'll mark this issue as taken and 'assign' it to you. I think once this issue is resolved, it'll probably warrant a minor release so that Windows users can get going with Glicky with a freshly built CLI!
