### ISSUE TITLE
Slightly broken UI in Firefox

### ISSUE THREAD

**Issue by dfosco** [alex-saunders/glicky#7]
Firefox:
![image](https://user-images.githubusercontent.com/3229933/56348658-38275a00-61c7-11e9-9745-4036101f31c7.png)

Chrome for comparison:

![image](https://user-images.githubusercontent.com/3229933/56348690-49706680-61c7-11e9-9539-c432d2e90d02.png)

This is Firefox developer edition (67.0b11 – 64-bit) running on MacOS High Sierra 10.13.4 (17E199)

**Comment by alex-saunders** [comment]
Hi @dfosco , thanks for pointing this out! I did test on Firefox but then made some pretty big UI changes to the Scripts view which probably lead to these problems 😖.

I'll get to work on fixing it right away
