### ISSUE TITLE
Library author avatar clipping in Safari

### ISSUE THREAD

**Issue by erikras** [alex-saunders/glicky#9]
Ain't CSS great?!? 😆

![Glicky 2019-04-18 15-33-30](https://user-images.githubusercontent.com/4396759/56364655-5c972c80-61ef-11e9-8c21-b1065d54a808.jpg)

**Comment by alex-saunders** [comment]
Damn CSS 😤

I'll bundle the fix for this in with the work for #7 

Thanks for raising this @erikras !
